# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T10:31:47+00:00



import argparse
import json
import os
from decimal import Decimal
from typing import *
from typing import Optional, Union

from autogen.mcp.mcp_proxy import MCPProxy
from autogen.mcp.mcp_proxy.security import (
    APIKeyHeader,
    BaseSecurity,
    UnsuportedSecurityStub,
)
from fastapi import Path, Query

from models import (
    ApiArticleArticleGymDetailsPutRequest,
    ApiArticleMeasureUnitPostRequest,
    ApiException,
    ApiMembershipGetResponse,
    ApiPackageSearchGetResponse,
    ApiResponse,
    ArticleDTO,
    DefaultResponseDTOOfArticleDTO,
    DefaultResponseDTOOfBoolean,
    DefaultResponseDTOOfGymDTO,
    DefaultResponseDTOOfInteger,
    DefaultResponseDTOOfListOfArticleSearchDTO,
    DefaultResponseDTOOfListOfPackageSearchDTO,
    DefaultResponseDTOOfPackageDTO,
    DefaultResponseDTOOfStatusDTO,
    DefaultResponseDTOOfString,
    GymArticleDetailsDTO,
    LoginDTO,
    MemberDTO,
    MessageStatus,
    PackageDTO,
    ProblemDetails,
    TestDTO,
    UserDTO,
)

app = MCPProxy(
    contact={
        'email': 'support@unicorn-solutions.com',
        'name': 'Unicorn Solutions',
        'url': 'https://unicorn-solutions.com',
    },
    description='Web API for TL mobile and web app',
    license={'name': 'Use under Unicorn', 'url': 'https://unicorn-solutions.com'},
    termsOfService='None',
    title='API',
    version='2020-08-10_6-22',
    servers=[
        {'url': 'https://tl-api.azurewebsites.net'},
        {'url': 'https://triviallife.azure-api.net/v1'},
    ],
)


@app.delete(
    '/api/Article',
    tags=['article_management'],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def article__delete(article_id: Optional[int] = Query(None, alias='ArticleId')):
    """
    Delete article from the system

    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api/Article',
    tags=['article_management'],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def article__post(body: ArticleDTO):
    """
    Add new article

    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.put(
    '/api/Article',
    tags=['article_management'],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def article__put(body: ArticleDTO):
    """
    update existing article

    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.put(
    '/api/Article/ArticleGymDetails',
    tags=['article_management'],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def article__update_article_gym_details(body: ApiArticleArticleGymDetailsPutRequest):
    """
    Add article details that associate with a Gym

    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/Article/GetAddons',
    tags=['gym_data_retrieval'],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def article__get_addons(
    search_text: Optional[str] = Query(None, alias='searchText'),
    gym_ids: Optional[str] = Query('-1', alias='gymIds'),
    type: Optional[str] = 'all',
    limit: Optional[int] = 100,
    offset: Optional[int] = 0,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/Article/GymArticle/{articleId}/{gymId}',
    tags=['article_management', 'gym_data_retrieval'],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def article__gym_article_details(
    article_id: int = Path(..., alias='articleId'),
    gym_id: int = Path(..., alias='gymId'),
):
    """
    Get Gym specific properties for article

    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api/Article/MeasureUnit',
    tags=['article_management'],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def article__add_measure_unit(body: ApiArticleMeasureUnitPostRequest):
    """
    Add measure unit
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/Article/MeasureUnits',
    tags=['gym_data_retrieval'],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def article__get_measure_units(type: Optional[str] = None):
    """
    Get mesure units
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/Article/RevenueAccounts',
    tags=['gym_data_retrieval'],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def article__get_revenue_accounts():
    """
    Get Revenue Accounts
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/Article/Search',
    tags=['article_management'],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def article__search(
    search_text: Optional[str] = Query(None, alias='searchText'),
    gym_id: Optional[int] = Query(-1, alias='gymId'),
    type: Optional[str] = 'all',
    order_by: Optional[str] = Query('1', alias='orderBy'),
    limit: Optional[int] = 100,
    offset: Optional[int] = 0,
    active_status: Optional[int] = Query(1, alias='activeStatus'),
):
    """
        Search articles
    It will only return basic information of article

    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.put(
    '/api/Article/UpdateStatus',
    tags=['article_management'],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def article__update_status(
    article_id: Optional[int] = Query(None, alias='ArticleId'),
    status: Optional[int] = None,
    user_name: Optional[str] = Query(None, alias='userName'),
):
    """
    Deactivate existing article
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/Article/{articleID}',
    tags=['article_management'],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def article_get(article_i_d: int = Path(..., alias='articleID')):
    """
        Get article details
    This will return all properties related to article entity

    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api/Auth/login',
    tags=['user_authentication', 'user_account_management'],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def auth__login(body: LoginDTO):
    """
    Authenticate and provide token for autherizations.

    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/Gym/{gymID}',
    tags=['gym_data_retrieval'],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def gym_get(gym_i_d: int = Path(..., alias='gymID')):
    """
        Get gym details
    This will return all properties related to gym entity

    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/Membership',
    tags=['membership_operations'],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def membership__get():
    """
        Get all of the members details
    This will return all properties related to member entity

    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api/Membership',
    tags=['membership_operations'],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def membership__post(body: MemberDTO):
    """
    Add new Member

    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete(
    '/api/Package',
    tags=['package_handling'],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def package__delete(package_id: Optional[int] = Query(None, alias='PackageId')):
    """
    Delete existing package

    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/Package',
    tags=['package_handling'],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def package__get(package_id: Optional[int] = Query(None, alias='packageId')):
    """
    Get package details by packageId

    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api/Package',
    tags=['package_handling'],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def package__post(body: PackageDTO):
    """
    Insert new package into the system

    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.put(
    '/api/Package',
    tags=['package_handling'],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def package__put(body: PackageDTO):
    """
    Update existing package by its ID

    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/Package/Search',
    tags=['package_handling'],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def package__search(
    search_text: Optional[str] = Query(None, alias='searchText'),
    gym_id: Optional[int] = Query(-1, alias='gymId'),
    type: Optional[str] = 'all',
    order_by: Optional[str] = Query('1', alias='orderBy'),
    limit: Optional[int] = 100,
    offset: Optional[int] = 0,
    active_status: Optional[int] = Query(1, alias='activeStatus'),
    category_id: Optional[int] = Query(-1, alias='categoryId'),
    startp_price: Optional[Decimal] = Query(0, alias='startpPrice'),
    end_price: Optional[Decimal] = Query(9999999, alias='endPrice'),
    request_source: Optional[int] = Query(1, alias='requestSource'),
):
    """
    Search packages

    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.put(
    '/api/Package/UpdateStatus',
    tags=['package_handling'],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def package__update_status(
    package_id: Optional[int] = Query(None, alias='packageId'),
    status: Optional[int] = 1,
    user_name: Optional[str] = Query('system', alias='userName'),
):
    """
    Status update of existing package
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/Status',
    tags=['package_handling'],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def status__get(message_id: Optional[str] = Query(None, alias='messageId')):
    """
    Get the current status of message
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/Test',
    tags=['gym_data_retrieval'],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def test_get():
    """
    Get the all Test objects.

    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/User',
    tags=['user_account_management'],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def user__get():
    """
        Get all Users detail
    This will return all properties related to User entity

    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api/User/registerUser',
    tags=['membership_operations', 'user_account_management'],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def user_register_user(
    user_id: Optional[int] = Query(None, alias='UserId'),
    account_number: Optional[str] = Query(None, alias='AccountNumber'),
    gym_number: Optional[str] = Query(None, alias='GymNumber'),
    external_entity_number: Optional[str] = Query(None, alias='ExternalEntityNumber'),
    name: Optional[str] = Query(None, alias='Name'),
    number: Optional[str] = Query(None, alias='Number'),
    introduce_by: Optional[int] = Query(None, alias='IntroduceBy'),
    guardian: Optional[int] = Query(None, alias='Guardian'),
    type_id: Optional[int] = Query(None, alias='TypeId'),
):
    """
    Register a new User

    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.put(
    '/api/User/updateuser',
    tags=['user_account_management', 'membership_operations'],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def user_update_user(
    user_id: Optional[int] = Query(None, alias='UserId'),
    account_number: Optional[str] = Query(None, alias='AccountNumber'),
    gym_number: Optional[str] = Query(None, alias='GymNumber'),
    external_entity_number: Optional[str] = Query(None, alias='ExternalEntityNumber'),
    name: Optional[str] = Query(None, alias='Name'),
    number: Optional[str] = Query(None, alias='Number'),
    introduce_by: Optional[int] = Query(None, alias='IntroduceBy'),
    guardian: Optional[int] = Query(None, alias='Guardian'),
    type_id: Optional[int] = Query(None, alias='TypeId'),
):
    """
    Update an exsisting User

    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="MCP Server")
    parser.add_argument(
        "transport",
        choices=["stdio", "sse", "streamable-http"],
        help="Transport mode (stdio, sse or streamable-http)",
    )
    args = parser.parse_args()

    if "CONFIG_PATH" in os.environ:
        config_path = os.environ["CONFIG_PATH"]
        app.load_configuration(config_path)

    if "CONFIG" in os.environ:
        config = os.environ["CONFIG"]
        app.load_configuration_from_string(config)

    if "SECURITY" in os.environ:
        security_params = BaseSecurity.parse_security_parameters_from_env(
            os.environ,
        )

        app.set_security_params(security_params)

    mcp_settings = json.loads(os.environ.get("MCP_SETTINGS", "{}"))

    app.get_mcp(**mcp_settings).run(transport=args.transport)
