# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T10:31:47+00:00

from __future__ import annotations

from datetime import datetime
from decimal import Decimal
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, ConfigDict, Field, RootModel, constr


class ApiResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    isError: Optional[bool] = None
    message: Optional[str] = None
    responseException: Optional[Any] = None
    result: Optional[Any] = None
    statusCode: Optional[int] = None
    version: Optional[str] = None


class ArticleSearchDTO(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    activeStatus: Optional[bool] = Field(None, description='Active Status ')
    applyForAllGyms: Optional[bool] = None
    articleId: Optional[int] = None
    createdDate: Optional[datetime] = None
    createdUser: Optional[str] = None
    description: Optional[str] = None
    measureUnit: Optional[str] = Field(None, description='MeasureUnit ')
    modifiedDate: Optional[datetime] = None
    modifiedUser: Optional[str] = None
    name: Optional[str] = None
    number: Optional[int] = None
    price: Optional[Decimal] = None
    sellingPrice: Optional[Decimal] = Field(
        None, description='Actual Selling price of the article '
    )
    tags: Optional[str] = None
    totalCount: Optional[int] = Field(
        None, description='total number of recode for particular search '
    )
    type: Optional[str] = Field(None, description='article type')


class DefaultResponseDTOOfBoolean(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    isError: Optional[bool] = None
    message: Optional[str] = None
    responseException: Optional[Any] = None
    result: Optional[bool] = None


class DefaultResponseDTOOfInteger(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    isError: Optional[bool] = None
    message: Optional[str] = None
    responseException: Optional[Any] = None
    result: Optional[int] = None


class DefaultResponseDTOOfListOfArticleSearchDTO(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    isError: Optional[bool] = None
    message: Optional[str] = None
    responseException: Optional[Any] = None
    result: Optional[List[ArticleSearchDTO]] = None


class DefaultResponseDTOOfString(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    isError: Optional[bool] = None
    message: Optional[str] = None
    responseException: Optional[Any] = None
    result: Optional[str] = None


class Exception(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    InnerException: Optional[Exception] = None
    Message: Optional[str] = None
    Source: Optional[str] = None
    StackTrace: Optional[str] = None


class GymArticleDetailsDTO(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    articleId: Optional[int] = None
    availableQty: Optional[Decimal] = None
    createdUser: Optional[str] = Field(None, description='Created User ')
    employeeDiscount: Optional[Decimal] = None
    employeePrice: Optional[Decimal] = None
    gymId: Optional[int] = Field(None, description='Gym Id where article is related ')
    gymIdList: Optional[str] = Field(
        None, description='GymId - Gym Id string with comma separated GymIds '
    )
    gymName: Optional[str] = Field(None, description='Gym Name')
    id: Optional[int] = None
    isDefault: Optional[bool] = Field(
        None, description='Set as the default values for the article '
    )
    isInventoryItem: Optional[bool] = None
    isObsolete: Optional[bool] = None
    modifiedUser: Optional[str] = Field(None, description='Modified user')
    reorderLevel: Optional[Decimal] = None
    revenueAccountId: Optional[int] = Field(None, description='Revenue account Id')
    sellingPrice: Optional[Decimal] = None


class GymDTO(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    externalGymNumber: Optional[int] = None
    gymId: Optional[int] = None
    gymName: Optional[str] = None
    location: Optional[str] = None


class LoginDTO(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    password: Optional[str] = None
    remember: Optional[bool] = None
    username: Optional[str] = None


class MeasureUnitDTO(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: Optional[int] = Field(None, description='Id of the table')
    name: Optional[str] = Field(None, description='Mesure Unit Type')
    type: Optional[str] = Field(
        None, description='Type of the article used with (all, service, item)'
    )


class MemberDTO(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: Optional[str] = None


class MessageStatus(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    messageId: Optional[str] = None
    referenceId: Optional[int] = None
    source: Optional[Any] = None
    statusId: Optional[int] = None
    statusText: Optional[str] = None


class PackageItemDTO(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    articleId: int = Field(
        ..., description='Refer to ArticleId in Article table in DB.\n            '
    )
    articleName: Optional[str] = Field(
        None,
        description='Name of the article(Addon) in a particular package.\n             read only\n            ',
    )
    articleNumber: Optional[int] = Field(
        None,
        description='Number assigned the article(Addon) in a particular package.\n             read only\n            ',
    )
    articlePrice: Optional[Decimal] = Field(
        None,
        description='Price of the article determined from that package.\nPrice of a same article can be varied from package to package.\n            ',
    )
    endOrder: Optional[int] = Field(
        None,
        description='Number of the installment this article is available to.\n            ',
    )
    isIncludeServiceInCharge: Optional[bool] = Field(
        None, description='Is Included in service charge '
    )
    measureUnit: Optional[str] = None
    numberOfItems: Optional[Decimal] = Field(
        None,
        description='How many article(Addon) is available for that package from that type.\n            ',
    )
    startOrder: Optional[int] = Field(
        None,
        description='Number of the installment this article is available from.\n            ',
    )


class PackageSearchDTO(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    activeStatus: Optional[bool] = Field(None, description='Active Status ')
    addonFee: Optional[Decimal] = Field(
        None,
        description='sum of addon fees.\nincoming values for this filed will ignore.\n            ',
    )
    applyForAllGyms: Optional[bool] = Field(
        None,
        description='Boolean value to indicate wheather package is available in all the gyms.\n            ',
    )
    bindingPeriod: Optional[int] = Field(
        None,
        description='Range of period a member is bound to the contract if he/she choose this package.\n            ',
    )
    createdDate: Optional[datetime] = Field(
        None, description='Package created DateTime.\n            '
    )
    createdUser: Optional[str] = Field(
        None, description='Package created user.\n            '
    )
    description: Optional[str] = Field(
        None,
        description='Common descriptions about package.If there are more instructions can be stored as comma separated values.\n            ',
    )
    features: Optional[str] = Field(
        None,
        description='What are the facilities, features available for package.ex:- wifi, ACm etc.Can be stored as comma seperated values.\n            ',
    )
    freeMonths: Optional[int] = Field(
        None,
        description='No of months gym member can come without payments.\n            ',
    )
    memberCanRemoveAddOns: Optional[bool] = Field(
        None,
        description='Boolean value to indicate member can remove already added addons if he choose this package.\n            ',
    )
    modifiedDate: Optional[datetime] = Field(
        None, description='Package last modified DateTime.\n            '
    )
    modifiedUser: Optional[str] = Field(
        None, description='Package last modified user.\n            '
    )
    monthlyFee: Optional[Decimal] = Field(
        None,
        description='Monthly installment fee if package is not fixed visit.\naddition of the servicefee and addon fees divided by binding period.\n            ',
    )
    numberOfVisits: Optional[int] = Field(
        None, description='No of visits for fixed package '
    )
    packageId: Optional[int] = None
    packageName: Optional[str] = None
    packageNumber: Optional[int] = None
    packageType: Optional[str] = Field(
        None,
        description='Package type can be either fixed visit or unlimited.\n            ',
    )
    registrationFee: Optional[Decimal] = Field(
        None, description='Registartion fee for the package at a gym.\n            '
    )
    serviceFee: Optional[Decimal] = Field(
        None,
        description='total Service charge of the package for entire period.\n            ',
    )
    tags: Optional[str] = Field(
        None,
        description='Comma separated string values in case of need of maintain some labels kind of stuff relevant to the package.\n            ',
    )
    totalCount: Optional[int] = Field(
        None, description='total number of recode for particular search '
    )
    totalPrice: Optional[Decimal] = Field(
        None,
        description='total price for the package including Addon fees, service fee and registration fee.\nincoming values for this field will ignore.\n            ',
    )


class ProblemDetails(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    detail: Optional[str] = None
    extensions: Optional[Dict[str, Any]] = None
    instance: Optional[str] = None
    status: Optional[int] = None
    title: Optional[str] = None
    type: Optional[str] = None


class StatusDTO(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    messageId: Optional[str] = Field(
        None, description='Reference id for status endpoint\n            '
    )
    statusText: Optional[str] = Field(
        None, description='Status of API Call\n            '
    )
    url: Optional[str] = Field(
        None, description='Relative url for stauts check\n            '
    )


class TestDTO(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: Optional[int] = Field(None, description='Id of the Test object\n            ')


class UserDTO(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    accountNumber: Optional[str] = Field(
        None,
        description='Account number of the user.It can be any stakeholder of the application.even can be a gym.\n            ',
    )
    externalEntityNumber: Optional[str] = Field(
        None,
        description='Entity number that make a relationship with BOX API DB.\n            ',
    )
    guardian: Optional[int] = Field(
        None,
        description='Gaurdian of the this user if he/she is under 18 years old.\n            ',
    )
    gymNumber: Optional[str] = Field(
        None, description='If this user is a gym, then the gym number.\n            '
    )
    introduceBy: Optional[int] = Field(
        None,
        description="If Someone introduced this user to the system, then that user's UserId.\n            ",
    )
    name: Optional[str] = Field(None, description='Name of the user.\n            ')
    number: Optional[str] = Field(
        None,
        description='Unique number maintain by application to idenify user.\n            ',
    )
    typeId: Optional[int] = Field(None, description='Type of the user.\n            ')
    userId: Optional[int] = Field(
        None,
        description='Indentity number(primary key) for user object. Generated in DB table when inserting a record.\n            ',
    )


class ValidationError(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    field: Optional[str] = None
    message: Optional[str] = None


class ApiArticleArticleGymDetailsPutRequest(RootModel[List[GymArticleDetailsDTO]]):
    root: List[GymArticleDetailsDTO]


class ApiArticleMeasureUnitPostRequest(RootModel[List[MeasureUnitDTO]]):
    root: List[MeasureUnitDTO]


class ApiMembershipGetResponse(RootModel[List[MemberDTO]]):
    root: List[MemberDTO]


class ApiException(Exception):
    customError: Optional[Any] = None
    errors: Optional[List[ValidationError]] = None
    isCustomErrorObject: Optional[bool] = None
    isModelValidatonError: Optional[bool] = None
    referenceDocumentLink: Optional[str] = None
    referenceErrorCode: Optional[str] = None
    statusCode: Optional[int] = None


class ArticleDTO(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    activeStatus: Optional[bool] = Field(None, description='Active Status ')
    applyForAllGyms: Optional[bool] = None
    articleId: Optional[int] = None
    availableGyms: List[GymDTO]
    availableQty: Optional[Decimal] = Field(None, description='Default AvailableQty')
    barcode: Optional[constr(min_length=0, max_length=100)] = None
    createdDate: Optional[datetime] = None
    createdUser: Optional[str] = None
    cronExpression: Optional[str] = Field(
        None, description='Access Schedule CRON Expression '
    )
    description: Optional[str] = None
    discount: Optional[Decimal] = None
    employeeDiscount: Optional[Decimal] = Field(
        None, description='Default EmployeeDiscount'
    )
    employeePrice: Optional[Decimal] = Field(None, description='Default EmployeePrice')
    gymArticles: Optional[List[GymArticleDetailsDTO]] = Field(
        None, description='Gym Customizations '
    )
    isAddOn: Optional[bool] = None
    isInventoryItem: Optional[bool] = Field(
        None, description='Default IsInventoryItem of the Article '
    )
    isObsolete: Optional[bool] = Field(
        None, description='Default IsObsolete of the Article '
    )
    measureUnit: constr(min_length=1)
    modifiedDate: Optional[datetime] = None
    modifiedUser: Optional[str] = None
    name: constr(min_length=0, max_length=100)
    number: Optional[int] = None
    price: Decimal
    reorderLevel: Optional[Decimal] = Field(None, description='Deafault ReorderLevel')
    revenueAccountId: Optional[int] = Field(None, description='Default Revenue account')
    sellingPrice: Optional[Decimal] = Field(None, description='Default SellingPrice')
    tags: Optional[constr(min_length=0, max_length=200)] = None
    type: constr(pattern=r'item|service|access', min_length=1)
    vat: Optional[Decimal] = None
    vatApplicable: Optional[bool] = Field(None, description='VAT Applicable ')


class DefaultResponseDTOOfArticleDTO(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    isError: Optional[bool] = None
    message: Optional[str] = None
    responseException: Optional[Any] = None
    result: Optional[ArticleDTO] = None


class DefaultResponseDTOOfGymDTO(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    isError: Optional[bool] = None
    message: Optional[str] = None
    responseException: Optional[Any] = None
    result: Optional[GymDTO] = None


class DefaultResponseDTOOfListOfPackageSearchDTO(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    isError: Optional[bool] = None
    message: Optional[str] = None
    responseException: Optional[Any] = None
    result: Optional[List[PackageSearchDTO]] = None


class DefaultResponseDTOOfPackageSearchDTO(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    isError: Optional[bool] = None
    message: Optional[str] = None
    responseException: Optional[Any] = None
    result: Optional[PackageSearchDTO] = None


class DefaultResponseDTOOfStatusDTO(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    isError: Optional[bool] = None
    message: Optional[str] = None
    responseException: Optional[Any] = None
    result: Optional[StatusDTO] = None


class PackageDTO(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    addOns: Optional[List[PackageItemDTO]] = Field(
        None,
        description='Extra articles list added to the given package.\n            ',
    )
    addonFee: Optional[Decimal] = Field(
        None,
        description='sum of addon fees.\nincoming values for this filed will ignore.\n            ',
    )
    applyForAllGyms: Optional[bool] = Field(
        None,
        description='Boolean value to indicate wheather package is available in all the gyms.\n            ',
    )
    availableGyms: Optional[List[GymDTO]] = Field(
        None, description='Gyms list where this package is available.\n            '
    )
    bindingPeriod: Optional[int] = Field(
        None,
        description='Range of period a member is bound to the contract if he/she choose this package.\n            ',
    )
    createdDate: Optional[datetime] = Field(
        None, description='Package created DateTime.\n            '
    )
    createdUser: Optional[str] = Field(
        None, description='Package created user.\n            '
    )
    description: Optional[str] = Field(
        None,
        description='Common descriptions about package.If there are more instructions \n             can be stored as comma separated values.\n            ',
    )
    endDate: Optional[datetime] = Field(
        None,
        description='End date of the package.After that package is not valid for use.\n            ',
    )
    expireInMonths: Optional[int] = Field(
        None,
        description='No of months the fixed package is valid for sale\n            ',
    )
    features: Optional[str] = Field(
        None,
        description='What are the facilities, features available for package.ex:- wifi,\nACm etc.Can be stored as comma seperated values.\n            ',
    )
    freeMonths: Optional[int] = Field(
        None,
        description='No of months gym member can come without payments.\n            ',
    )
    instructionsToGymUsers: Optional[str] = Field(
        None,
        description='Instruction to the gym members relevant to the package.\n             If there are more instructions can be stored as comma seperated values.\n            ',
    )
    instructionsToWebUsers: Optional[str] = Field(
        None,
        description='Instruction to the MRM members relevant to the package.\n             If there are more instructions can be stored as comma seperated values.\n            ',
    )
    isActive: Optional[bool] = Field(
        None,
        description='Boolean value to indicate this package is still active or not.\n            ',
    )
    isAtg: Optional[bool] = Field(
        None,
        description='Boolean value to indicate ATG transaction from bank is applicable or not.\n            ',
    )
    isAutoRenew: Optional[bool] = Field(
        None,
        description='Boolean value to indicate the contract will auto renew after expiration \n             if this package would be chosen.\n            ',
    )
    isFirstMonthFree: Optional[bool] = Field(
        None,
        description='Boolean value to indicate if the first month charges is free.\n            ',
    )
    isRegistrationFee: Optional[bool] = Field(
        None,
        description='Boolean value to indicate this package has registration fee or not.\n            ',
    )
    isRestAmount: Optional[bool] = Field(
        None,
        description='Boolean value to indicate rest amount is applicable or not.\n            ',
    )
    isShownInMobile: Optional[bool] = Field(
        None,
        description='Boolean value to indicate package is visible in Mobile App or not.\n            ',
    )
    isSponsorPackage: Optional[bool] = Field(
        None,
        description='Boolean value to indicate package can be sponsored or not by other party.\n            ',
    )
    maximumGiveAwayRestAmount: Optional[Decimal] = Field(
        None,
        description='If a member join the gym middle of a month via this package, \n             what is the maximum amount of price can be neglected from payment from the member.\n            ',
    )
    memberCanAddAddOns: Optional[bool] = Field(
        None,
        description='Boolean value to indicate member can add extra addons he wish if he choose this package.\n            ',
    )
    memberCanLeaveWithinFreePeriod: Optional[bool] = Field(
        None,
        description='Boolean value to indicate if member can leave from contract within \n             free period if he/she choose this package.\n            ',
    )
    memberCanRemoveAddOns: Optional[bool] = Field(
        None,
        description='Boolean value to indicate member can remove already added addons if he choose this package.\n            ',
    )
    modifiedDate: Optional[datetime] = Field(
        None, description='Package last modified DateTime.\n            '
    )
    modifiedUser: Optional[str] = Field(
        None, description='Package last modified user.\n            '
    )
    monthlyFee: Optional[Decimal] = Field(
        None,
        description='Monthly installment fee if package is not fixed visit.\naddition of the servicefee and addon fees divided by binding period.\n             read only\n            ',
    )
    nextPackageNumber: Optional[int] = Field(
        None,
        description='Next Package the contract continue after the binding period of this package.\n            ',
    )
    numberOfInstallments: Optional[int] = Field(
        None,
        description='Maximum Number of installment a member can divide the package price/cost to pay.\n            ',
    )
    numberOfVisits: Optional[int] = Field(
        None,
        description='If package is fixed visit type, then how many visits are available for this package.\n            ',
    )
    packageId: Optional[int] = None
    packageName: constr(min_length=1)
    packageNumber: Optional[str] = None
    packageType: constr(pattern=r'fixedvisit|unlimited', min_length=1) = Field(
        ...,
        description='Package type can be either fixed visit or unlimited.\n            ',
    )
    perVisitPrice: Optional[Decimal] = Field(
        None, description='Cost/Price of the single visit to gym.\n            '
    )
    registrationFee: Decimal = Field(
        ...,
        description='Registartion fee for the package at a gym.\n             read only\n            ',
    )
    serviceFee: Decimal = Field(
        ...,
        description='total Service charge of the package for entire period.\n            ',
    )
    shownInWeb: Optional[bool] = Field(
        None,
        description='Boolean value to show this package in MRM system or not.\n            ',
    )
    startDate: Optional[datetime] = Field(
        None, description='Start date of the package.\n            '
    )
    tags: Optional[str] = Field(
        None,
        description='Comma separated string values in case of need of maintain some labels kind of \n             stuff relevant to the package.\n            ',
    )
    totalPrice: Optional[Decimal] = Field(
        None,
        description='total price for the package including Addon fees, service fee and registration fee.\nincoming values for this field will ignore.\n            ',
    )


class ApiPackageSearchGetResponse(
    RootModel[List[DefaultResponseDTOOfPackageSearchDTO]]
):
    root: List[DefaultResponseDTOOfPackageSearchDTO]


class DefaultResponseDTOOfPackageDTO(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    isError: Optional[bool] = None
    message: Optional[str] = None
    responseException: Optional[Any] = None
    result: Optional[PackageDTO] = None


Exception.model_rebuild()
